### ISSUE TITLE
longBylineText occassionaly gives AttributeError

### ISSUE THREAD

**Issue by Jigoku** [joetats/youtube_search#28]
Some search terms will fail, such as this example for "melon buffet". This happens fairly often with many different query's.

```python
from youtube_search import YoutubeSearch
search = YoutubeSearch('melon buffet', max_results=10).to_json()
print (search)
```

```
Traceback (most recent call last):
  File "./yt.py", line 6, in <module>
    search = YoutubeSearch('melon buffet', max_results=10)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_search/__init__.py", line 10, in __init__
    self.videos = self.search()
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_search/__init__.py", line 19, in search
    results = self.parse_html(response)
  File "/home/pi/.local/lib/python3.7/site-packages/youtube_search/__init__.py", line 47, in parse_html
    res["channel"] = video_data.get("longBylineText", {}).get("runs", [[{}]])[0].get("text", None)
AttributeError: 'list' object has no attribute 'get'
```

Commenting out this line https://github.com/joetats/youtube_search/blob/e021809d322619a61dab6c35362211c64e35e058/youtube_search/__init__.py#L47 is a temporary fix. I'm not sure on why this is happening for some queries?

**Comment by joetats** [comment]
I can't seem to recreate this at the moment - maybe youtube changed something in the time it took me to get back here? Let me see if I can script up something to keep sending random searches and see if anything pops up.

Based on the issue, it appears that one of the children of video_data is a list and not a dict, so there might be some logic needed to keep checking down the list. I'll plan on a major update to try and handle these weird data types without adding too many checks.
